"""initial schema

Revision ID: 6b910adadcef
Revises: 
Create Date: 2025-11-21 01:22:27.546282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6b910adadcef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('kyc_applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'APPROVED', 'REVIEW_REQUIRED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.application_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('raw_file_path', sa.Text(), nullable=False),
    sa.Column('extracted_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.application_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('embedding_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.application_id'], ),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_table('explainability',
    sa.Column('explain_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('shap_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.application_id'], ),
    sa.PrimaryKeyConstraint('explain_id')
    )
    op.create_table('risk_scores',
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('feature_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.application_id'], ),
    sa.PrimaryKeyConstraint('risk_score_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    op.drop_table('explainability')
    op.drop_table('embeddings')
    op.drop_table('documents')
    op.drop_table('audit_logs')
    op.drop_table('kyc_applications')
    op.drop_table('users')
    # ### end Alembic commands ###
