"""add entity fields

Revision ID: ac015fd27f69
Revises: 6b910adadcef
Create Date: 2025-11-23 20:17:04.035664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac015fd27f69'
down_revision: Union[str, Sequence[str], None] = '6b910adadcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_applications', sa.Column('extracted_name', sa.String(length=255), nullable=True))
    op.add_column('kyc_applications', sa.Column('extracted_dob', sa.String(length=50), nullable=True))
    op.add_column('kyc_applications', sa.Column('extracted_address', sa.Text(), nullable=True))
    op.add_column('kyc_applications', sa.Column('extracted_id_number', sa.String(length=100), nullable=True))
    op.add_column('kyc_applications', sa.Column('entity_mismatches', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_applications', 'entity_mismatches')
    op.drop_column('kyc_applications', 'extracted_id_number')
    op.drop_column('kyc_applications', 'extracted_address')
    op.drop_column('kyc_applications', 'extracted_dob')
    op.drop_column('kyc_applications', 'extracted_name')
    # ### end Alembic commands ###
